name: ent
description: Entando ent cli tool
inputs:
  ent-command: # id of input
    description: 'ent command to run'
    required: true
    default: ''
runs:
  using: 'docker'
  image: docker://registry.hub.docker.com/entando/ent:7.1.3_gha
  args:
    - ${{ inputs.ent-command }}

